#!/usr/bin/env python3
"""
Convert hands from database to LIN format for DD solver
"""
import json

def hand_to_lin(hand):
    """Convert hand dict {S: 'QJ8', H: '987', D: 'K5', C: 'AK842'} to LIN format"""
    if not hand:
        return ''
    suits = ['S', 'H', 'D', 'C']
    lin = ''
    for suit in suits:
        cards = hand.get(suit, '')
        lin += suit + (cards if cards else '-')
    return lin

def vuln_to_lin(vuln_str):
    """Convert vulnerability string to LIN code"""
    vuln_map = {
        'None': 'n',
        'E': 'e', 
        'N-S': 'o',
        'E-W': 'e',
        'Both': 'b'
    }
    return vuln_map.get(vuln_str, 'n')

def dealer_to_code(dealer):
    """Convert dealer position to LIN code"""
    return dealer.lower() if dealer else 'n'

def create_lin_record(board_num, board_data):
    """Create a LIN record for a single board"""
    dealer = dealer_to_code(board_data.get('dealer', 'N'))
    vuln = vuln_to_lin(board_data.get('vulnerability', 'None'))
    
    hands = board_data.get('hands', {})
    north_lin = hand_to_lin(hands.get('North'))
    east_lin = hand_to_lin(hands.get('East'))
    south_lin = hand_to_lin(hands.get('South'))
    west_lin = hand_to_lin(hands.get('West'))
    
    # Format: qx|o[num]|md|[dealer][hands]|sv|[vuln]|ah|Board [num]|pg||
    record = f"qx|o{board_num}|md|{dealer}{north_lin},{east_lin},{south_lin},{west_lin},|sv|{vuln}|ah|Board {board_num}|pg||"
    
    return record

def main():
    db_file = r"c:\Users\metin\Desktop\BRIC\app\www\hands_database.json"
    
    with open(db_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Get all boards
    boards = data['events']['hosgoru_04_01_2026']['boards']
    
    lin_content = "% Generated by Bridge DD Solver Converter\nvg|Hoşgörü Pazar Simultane|pg||\n"
    
    for board_num in sorted(boards.keys(), key=lambda x: int(x)):
        board_data = boards[board_num]
        record = create_lin_record(board_num, board_data)
        lin_content += record + " "
    
    # Save to file
    output_file = r"c:\Users\metin\Desktop\BRIC\boards_for_solver.lin"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(lin_content)
    
    print(f"Created LIN file: {output_file}")
    
    # Show preview
    print("\nFirst 3 boards in LIN format:")
    for board_num in sorted(boards.keys(), key=lambda x: int(x))[:3]:
        board_data = boards[board_num]
        record = create_lin_record(board_num, board_data)
        print(f"Board {board_num}: {record[:150]}...")

if __name__ == '__main__':
    main()
