#!/bin/bash
# PythonAnywhere Setup Script

echo "🚀 BRIC on PythonAnywhere - Setup Guide"
echo "======================================="
echo ""
echo "1. Create Account:"
echo "   → Go to https://www.pythonanywhere.com"
echo "   → Sign up with GitHub or email"
echo ""
echo "2. Create Web App:"
echo "   → Web tab → Add a new web app"
echo "   → Select Python 3.10"
echo ""
echo "3. Clone Repository:"
echo "   → Bash console:"
echo "   git clone https://github.com/metonline/mgbric.git"
echo "   cd mgbric"
echo ""
echo "4. Install Dependencies:"
echo "   pip install -r requirements.txt"
echo ""
echo "5. Create/Update WSGI:"
echo "   → Edit wsgi.py (provided)"
echo "   → Replace YOUR_USERNAME with your PythonAnywhere username"
echo ""
echo "6. Configure Web App:"
echo "   → Web tab → Your app → Configure"
echo "   - Source code: /home/YOUR_USERNAME/mgbric"
echo "   - WSGI file: /home/YOUR_USERNAME/mgbric/wsgi.py"
echo ""
echo "7. Reload:"
echo "   → Web tab → Click Reload button"
echo ""
echo "8. Visit:"
echo "   → https://YOUR_USERNAME.pythonanywhere.com"
echo ""
echo "✅ Done!"
